version: '2'
services:
    applications:
        image: tianon/true
        volumes:
            - ../:/var/www/html
    ws:
        container_name: ws
        image: nginx:latest
        ports:
            - "8080:80"
        volumes_from: 
            - applications
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/log:/var/nginx/logs
        links:
            - php:php
            - redis:redis
    php:
        container_name: php
        build:
            context: ./php-fpm
        volumes_from:
            - applications
        volumes:
            - ./php-fpm/conf.d:/usr/local/etc/php/conf.d
        ports:
            - "9000:9000"
    redis:
        container_name: redis
        build: ./redis
        volumes:
            - ./redis/data:/data
        ports:
            - "6379:6379"