version: '2'
services:
    applications:
        image: tianon/true
        volumes:
            - ../:/var/www/html
        extra_hosts:
            - "web:10.0.0.1"

    ws:
        container_name: ws
        image: nginx:latest
        ports:
            - "8080:80"
        volumes_from: 
            - applications
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/log:/var/nginx/logs
        extra_hosts:
            - "web:10.0.0.1"
        links:
            - php
            - redis
    php:
        container_name: php
        build:
            context: ./php-fpm
        volumes_from:
            - applications
        volumes:
            - ./php-fpm/conf.d:/usr/local/etc/php/conf.d
    redis:
        container_name: redis
        build: ./redis
        volumes:
            - ./redis/data:/data
        ports:
            - "63790:6379"
